version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: docshare-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: docshare
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - docshare-network

  # Backend API
  backend:
    build:
      context: ../../LieuKienAn-Backend
      dockerfile: ../TruongHoangGiang-DevOps/docker/backend/Dockerfile
    container_name: docshare-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/docshare?authSource=admin
      JWT_SECRET: your-production-jwt-secret-key
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - docshare-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application
  frontend:
    build:
      context: ../../TruongMyDuyen-Frontend
      dockerfile: ../TruongHoangGiang-DevOps/docker/frontend/Dockerfile
    container_name: docshare-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - docshare-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: docshare-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/sites-available:/etc/nginx/sites-available:ro
      - ../nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - docshare-network

volumes:
  mongodb_data:
  backend_uploads:

networks:
  docshare-network:
    driver: bridge
