version: '3.8'

services:
  # MongoDB Database for Development
  mongodb-dev:
    image: mongo:7.0
    container_name: docshare-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: devpassword
      MONGO_INITDB_DATABASE: docshare_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - docshare-dev-network

  # Backend API for Development
  backend-dev:
    build:
      context: ../../LieuKienAn-Backend
      dockerfile: ../TruongHoangGiang-DevOps/docker/backend/Dockerfile.dev
    container_name: docshare-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:devpassword@mongodb-dev:27017/docshare_dev?authSource=admin
      JWT_SECRET: dev-jwt-secret-key
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ../../LieuKienAn-Backend:/app
      - /app/node_modules
      - backend_dev_uploads:/app/uploads
    depends_on:
      - mongodb-dev
    networks:
      - docshare-dev-network
    command: npm run dev

  # Frontend Application for Development
  frontend-dev:
    build:
      context: ../../TruongMyDuyen-Frontend
      dockerfile: ../TruongHoangGiang-DevOps/docker/frontend/Dockerfile.dev
    container_name: docshare-frontend-dev
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ../../TruongMyDuyen-Frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend-dev
    networks:
      - docshare-dev-network
    command: npm run dev

volumes:
  mongodb_dev_data:
  backend_dev_uploads:

networks:
  docshare-dev-network:
    driver: bridge
